batch_size: 32
dilation_rates:
- 1
- 2
- 4
- 8
dropout: 0.1302400159798105
early_stop_patience: 20
edge_threshold: 0.25
hidden_dim: 128
inception_depthwise: true
inception_use_pool_branch: false
kernel_size: 3
lambda_l1: 0.001
lambda_prior: 0.01
learning_rate: 0.008629954524173344
log_interval: 1
lr_adj: 0.0005
model_save_path: gcntcn_best.pth
num_epochs: 200
optuna_enabled: true
optuna_n_trials: 100
optuna_target_metric: rmse
optuna_timeout: 3600
output_dir: ./data/processed_data
random_seed: 42
save_visuals: true
visual_output_dir: ./optuna_best_output
visualize_samples: 100
warmup_epochs: 5
window_size: 16
